In [12]:
import pandas as pd
import numpy as np
df=pd.read_csv('india_job_market_2024_2026.csv')
df.head(100)

,Job_ID,Job_Title,Company,Company_Type,Industry,City,Location_Tier,Experience_Level,Job_Type,Work_Mode,Salary_LPA,Skills_Required,Education_Required,Openings,Applicants,Company_Rating,Date_Posted
0,IND2025000,Android Developer,Tech Mahindra,MNC,Information Technology,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,30.9,"Kotlin, Java, REST APIs",M.Tech/M.E.,3,276,4.0,31-10-2025
1,IND2025001,QA Engineer,Dream11,Indian Unicorn,Information Technology,Lucknow,Tier 2,Senior (6-10 yrs),Full-Time,Hybrid,58.6,"Selenium, Manual Testing, Postman, API Testing...",B.Tech/B.E.,3,325,4.0,19-05-2025
2,IND2025002,Business Analyst,HAL,PSU/Govt,EdTech,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,18.4,"JIRA, Excel, Power BI",MCA,5,559,3.6,21-08-2024
3,IND2025003,Cybersecurity Analyst,Groww,Startup,Information Technology,Mumbai,Tier 1,Mid (3-6 yrs),Full-Time,Hybrid,21.7,"Penetration Testing, Python, Ethical Hacking, ...",BCA,3,184,3.5,18-03-2026
4,IND2025004,Python Developer,Oracle,MNC,EdTech,Remote,Remote,Junior (1-3 yrs),Full-Time,Remote,8.0,"Docker, REST APIs, AWS, PostgreSQL",MCA,1,64,3.9,25-10-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,IND2025095,Data Analyst,Deloitte,MNC,Information Technology,Remote,Remote,Junior (1-3 yrs),Full-Time,On-Site,9.6,"Data Visualization, Tableau, Power BI, SQL, Excel",B.Tech/B.E.,3,174,3.8,23-07-2024
96,IND2025096,Data Analyst,Zoho,Indian Unicorn,FinTech,Remote,Remote,Mid (3-6 yrs),Full-Time,Remote,24.3,"Python, Power BI, Excel, Data Visualization, S...",MCA,2,63,2.9,04-11-2025
97,IND2025097,UI/UX Designer,BrowserStack,Startup,FinTech,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,37.4,"Prototyping, User Research, Wireframing, CSS, ...",B.Tech/B.E.,5,382,4.0,30-09-2025
98,IND2025098,Power BI Developer,Zoho,Indian Unicorn,Automobile,Remote,Remote,Mid (3-6 yrs),Full-Time,Hybrid,17.0,"ETL, Power BI, Data Modeling, Excel",M.Tech/M.E.,2,206,4.1,22-11-2024
99,IND2025099,DevOps Engineer,Zerodha,Startup,Information Technology,Pune,Tier 1,Fresher (0-1 yr),Full-Time,On-Site,4.8,"Ansible, CI/CD, Linux, Docker, Kubernetes, Jen...",MCA,3,358,3.7,30-12-2024

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job_ID              5000 non-null   str
 1   Job_Title           5000 non-null   str
 2   Company             5000 non-null   str
 3   Company_Type        5000 non-null   str
 4   Industry            5000 non-null   str
 5   City                5000 non-null   str
 6   Location_Tier       5000 non-null   str
 7   Experience_Level    5000 non-null   str
 8   Job_Type            5000 non-null   str
 9   Work_Mode           5000 non-null   str
 10  Salary_LPA          5000 non-null   float64
 11  Skills_Required     5000 non-null   str
 12  Education_Required  5000 non-null   str
 13  Openings            5000 non-null   int64
 14  Applicants          5000 non-null   int64
 15  Company_Rating      5000 non-null   float64
 16  Date_Posted         5000 non-null   str
dtypes: float64(2), int64(2), str(13)
memory usage: 664.2 KB

### Creation of Company Table

In [14]:
Company_table=df[["Company","Company_Type","Industry"]].drop_duplicates().reset_index(drop=True)
Company_table

           Company    Company_Type                Industry
0    Tech Mahindra             MNC  Information Technology
1          Dream11  Indian Unicorn  Information Technology
2              HAL        PSU/Govt                  EdTech
3            Groww         Startup  Information Technology
4           Oracle             MNC                  EdTech
..             ...             ...                     ...
709         Meesho  Indian Unicorn   Media & Entertainment
710         Zomato  Indian Unicorn               Logistics
711            IBM             MNC                  Gaming
712      Cognizant             MNC                 Telecom
713           CRED  Indian Unicorn              Automobile

[714 rows x 3 columns]

In [15]:
Company_table.columns

Index(['Company', 'Company_Type', 'Industry'], dtype='str')

In [16]:
Company_table.insert(0, "Company_ID", ["C_" + str(i) for i in range(1, len(Company_table) + 1)])

In [17]:
Company_table

    Company_ID        Company    Company_Type                Industry
0          C_1  Tech Mahindra             MNC  Information Technology
1          C_2        Dream11  Indian Unicorn  Information Technology
2          C_3            HAL        PSU/Govt                  EdTech
3          C_4          Groww         Startup  Information Technology
4          C_5         Oracle             MNC                  EdTech
..         ...            ...             ...                     ...
709      C_710         Meesho  Indian Unicorn   Media & Entertainment
710      C_711         Zomato  Indian Unicorn               Logistics
711      C_712            IBM             MNC                  Gaming
712      C_713      Cognizant             MNC                 Telecom
713      C_714           CRED  Indian Unicorn              Automobile

[714 rows x 4 columns]

### Creation of Location Table

In [18]:
Location_table=df[["City","Location_Tier"]].drop_duplicates()

In [19]:
Location_table.insert(0,"Location_ID",["L_"+ str(i) for i in range(1,len(Location_table)+1)])

In [20]:
Location_table

    Location_ID         City Location_Tier
0           L_1       Remote        Remote
1           L_2      Lucknow        Tier 2
3           L_3       Mumbai        Tier 1
5           L_4       Indore        Tier 2
7           L_5         Pune        Tier 1
9           L_6        Delhi        Tier 1
11          L_7    Hyderabad        Tier 1
15          L_8  Bhubaneswar        Tier 2
17          L_9    Bangalore        Tier 1
21         L_10      Chennai        Tier 1
33         L_11        Kochi        Tier 2
36         L_12       Jaipur        Tier 2
37         L_13      Kolkata        Tier 2
43         L_14   Coimbatore        Tier 2
68         L_15   Chandigarh        Tier 2
109        L_16    Ahmedabad        Tier 2
110        L_17       Nagpur        Tier 2

In [21]:
Fact_table=df.merge(Company_table,on=["Company", "Company_Type", "Industry"], how='left')

In [22]:
Fact_table = Fact_table.merge(Location_table,on=["City", "Location_Tier"], how='left')

In [23]:
Fact_table

,Job_ID,Job_Title,Company,Company_Type,Industry,City,Location_Tier,Experience_Level,Job_Type,Work_Mode,Salary_LPA,Skills_Required,Education_Required,Openings,Applicants,Company_Rating,Date_Posted,Company_ID,Location_ID
0,IND2025000,Android Developer,Tech Mahindra,MNC,Information Technology,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,30.9,"Kotlin, Java, REST APIs",M.Tech/M.E.,3,276,4.0,31-10-2025,C_1,L_1
1,IND2025001,QA Engineer,Dream11,Indian Unicorn,Information Technology,Lucknow,Tier 2,Senior (6-10 yrs),Full-Time,Hybrid,58.6,"Selenium, Manual Testing, Postman, API Testing...",B.Tech/B.E.,3,325,4.0,19-05-2025,C_2,L_2
2,IND2025002,Business Analyst,HAL,PSU/Govt,EdTech,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,18.4,"JIRA, Excel, Power BI",MCA,5,559,3.6,21-08-2024,C_3,L_1
3,IND2025003,Cybersecurity Analyst,Groww,Startup,Information Technology,Mumbai,Tier 1,Mid (3-6 yrs),Full-Time,Hybrid,21.7,"Penetration Testing, Python, Ethical Hacking, ...",BCA,3,184,3.5,18-03-2026,C_4,L_3
4,IND2025004,Python Developer,Oracle,MNC,EdTech,Remote,Remote,Junior (1-3 yrs),Full-Time,Remote,8.0,"Docker, REST APIs, AWS, PostgreSQL",MCA,1,64,3.9,25-10-2024,C_5,L_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,IND2029995,Backend Developer,BEL,PSU/Govt,Media & Entertainment,Jaipur,Tier 2,Fresher (0-1 yr),Full-Time,Hybrid,4.5,"PostgreSQL, Java, Django, MongoDB, Docker",B.Tech/B.E.,2,72,4.2,11-03-2025,C_428,L_12
4996,IND2029996,React Developer,Google,MNC,Manufacturing,Remote,Remote,Fresher (0-1 yr),Full-Time,Remote,4.3,"TypeScript, React, JavaScript, Redux, Next.js",B.Tech/B.E.,1,76,4.0,30-12-2024,C_319,L_1
4997,IND2029997,QA Engineer,BHEL,PSU/Govt,FinTech,Remote,Remote,Mid (3-6 yrs),Contract,Remote,10.5,"Python, API Testing, Manual Testing, JIRA",B.Tech/B.E.,2,72,3.1,23-02-2026,C_66,L_1
4998,IND2029998,Frontend Developer,Byju's,Indian Unicorn,FinTech,Remote,Remote,Mid (3-6 yrs),Internship,On-Site,1.6,"Tailwind CSS, Figma, React, JavaScript, TypeSc...",BCA,3,187,3.9,26-04-2025,C_193,L_1
4999,IND2029999,Power BI Developer,PhonePe,Indian Unicorn,Manufacturing,Mumbai,Tier 1,Mid (3-6 yrs),Full-Time,On-Site,25.2,"ETL, Azure, Power BI",B.Tech/B.E.,1,110,4.3,13-08-2025,C_349,L_3

In [24]:
Fact_table.drop(columns=["Company","Company_Type","Industry","City","Location_Tier"],inplace=True)

In [25]:
Fact_table

,Job_ID,Job_Title,Experience_Level,Job_Type,Work_Mode,Salary_LPA,Skills_Required,Education_Required,Openings,Applicants,Company_Rating,Date_Posted,Company_ID,Location_ID
0,IND2025000,Android Developer,Senior (6-10 yrs),Full-Time,Remote,30.9,"Kotlin, Java, REST APIs",M.Tech/M.E.,3,276,4.0,31-10-2025,C_1,L_1
1,IND2025001,QA Engineer,Senior (6-10 yrs),Full-Time,Hybrid,58.6,"Selenium, Manual Testing, Postman, API Testing...",B.Tech/B.E.,3,325,4.0,19-05-2025,C_2,L_2
2,IND2025002,Business Analyst,Senior (6-10 yrs),Full-Time,Remote,18.4,"JIRA, Excel, Power BI",MCA,5,559,3.6,21-08-2024,C_3,L_1
3,IND2025003,Cybersecurity Analyst,Mid (3-6 yrs),Full-Time,Hybrid,21.7,"Penetration Testing, Python, Ethical Hacking, ...",BCA,3,184,3.5,18-03-2026,C_4,L_3
4,IND2025004,Python Developer,Junior (1-3 yrs),Full-Time,Remote,8.0,"Docker, REST APIs, AWS, PostgreSQL",MCA,1,64,3.9,25-10-2024,C_5,L_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,IND2029995,Backend Developer,Fresher (0-1 yr),Full-Time,Hybrid,4.5,"PostgreSQL, Java, Django, MongoDB, Docker",B.Tech/B.E.,2,72,4.2,11-03-2025,C_428,L_12
4996,IND2029996,React Developer,Fresher (0-1 yr),Full-Time,Remote,4.3,"TypeScript, React, JavaScript, Redux, Next.js",B.Tech/B.E.,1,76,4.0,30-12-2024,C_319,L_1
4997,IND2029997,QA Engineer,Mid (3-6 yrs),Contract,Remote,10.5,"Python, API Testing, Manual Testing, JIRA",B.Tech/B.E.,2,72,3.1,23-02-2026,C_66,L_1
4998,IND2029998,Frontend Developer,Mid (3-6 yrs),Internship,On-Site,1.6,"Tailwind CSS, Figma, React, JavaScript, TypeSc...",BCA,3,187,3.9,26-04-2025,C_193,L_1
4999,IND2029999,Power BI Developer,Mid (3-6 yrs),Full-Time,On-Site,25.2,"ETL, Azure, Power BI",B.Tech/B.E.,1,110,4.3,13-08-2025,C_349,L_3

### Connecting to postgresql database and loading

In [26]:
! pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in C:\Users\DONGRI ASHMANJUM\miniconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: psycopg2-binary in C:\Users\DONGRI ASHMANJUM\miniconda3\Lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in C:\Users\DONGRI ASHMANJUM\miniconda3\Lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\DONGRI ASHMANJUM\miniconda3\Lib\site-packages (from sqlalchemy) (4.15.0)

In [27]:
from sqlalchemy import create_engine

In [28]:

from sqlalchemy import create_engine
from sqlalchemy.engine import URL

url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="Ashmanjum@04",
    host="localhost",
    port=5432,
    database="job_market_db"
)

engine = create_engine(url)

In [29]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT version();"))
    print(result.fetchone())

('PostgreSQL 18.4 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit',)

In [30]:
Company_table.columns.tolist()

['Company_ID', 'Company', 'Company_Type', 'Industry']

In [31]:
Location_table.columns.tolist()

['Location_ID', 'City', 'Location_Tier']

In [32]:
Fact_table.columns.tolist()

['Job_ID',
 'Job_Title',
 'Experience_Level',
 'Job_Type',
 'Work_Mode',
 'Salary_LPA',
 'Skills_Required',
 'Education_Required',
 'Openings',
 'Applicants',
 'Company_Rating',
 'Date_Posted',
 'Company_ID',
 'Location_ID']

In [51]:
Company_table.columns = [
    "company_id",
    "company",
    "company_type",
    "industry"
]

Location_table.columns = [
    "location_id",
    "city",
    "location_tier"
]

Fact_table.columns = [
    "job_id",
    "job_title",
    "experience_level",
    "job_type",
    "work_mode",
    "salary_lpa",
    "skills_required",
    "education_required",
    "openings",
    "applicants",
    "company_rating",
    "date_posted",
    "company_id",
    "location_id"
]

In [54]:
print(Company_table.columns)
print(Location_table.columns)
print(Fact_table.columns)

Index(['company_id', 'company', 'company_type', 'industry'], dtype='str')
Index(['location_id', 'city', 'location_tier'], dtype='str')
Index(['job_id', 'job_title', 'experience_level', 'job_type', 'work_mode',
       'salary_lpa', 'skills_required', 'education_required', 'openings',
       'applicants', 'company_rating', 'date_posted', 'company_id',
       'location_id'],
      dtype='str')

In [59]:
from sqlalchemy import text

create_tables = """

-- Drop existing tables
DROP TABLE IF EXISTS fact_table CASCADE;
DROP TABLE IF EXISTS company_table CASCADE;
DROP TABLE IF EXISTS location_table CASCADE;

----------------------------------------------------
-- Company Dimension
----------------------------------------------------

CREATE TABLE company_table
(
    company_id VARCHAR(20) PRIMARY KEY,
    company VARCHAR(255) NOT NULL,
    company_type VARCHAR(100),
    industry VARCHAR(100)
);

----------------------------------------------------
-- Location Dimension
----------------------------------------------------

CREATE TABLE location_table
(
    location_id VARCHAR(20) PRIMARY KEY,
    city VARCHAR(100),
    location_tier VARCHAR(50)
);

----------------------------------------------------
-- Fact Table
----------------------------------------------------

CREATE TABLE fact_table
(
    job_id VARCHAR(20) PRIMARY KEY,

    job_title VARCHAR(255),
    experience_level VARCHAR(100),
    job_type VARCHAR(50),
    work_mode VARCHAR(50),

    salary_lpa DECIMAL(10,2),

    skills_required TEXT,

    education_required VARCHAR(255),

    openings INT,

    applicants INT,

    company_rating DECIMAL(3,2),
    date_posted DATE,

    company_id VARCHAR(20),
    location_id VARCHAR(20),

    CONSTRAINT fk_company
        FOREIGN KEY(company_id)
        REFERENCES company_table(company_id),

    CONSTRAINT fk_location
        FOREIGN KEY(location_id)
        REFERENCES location_table(location_id)
);

"""

with engine.begin() as conn:
    conn.execute(text(create_tables))

print("Tables created successfully.")

Tables created successfully.

In [60]:
Fact_table.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_id              5000 non-null   str
 1   job_title           5000 non-null   str
 2   experience_level    5000 non-null   str
 3   job_type            5000 non-null   str
 4   work_mode           5000 non-null   str
 5   salary_lpa          5000 non-null   float64
 6   skills_required     5000 non-null   str
 7   education_required  5000 non-null   str
 8   openings            5000 non-null   int64
 9   applicants          5000 non-null   int64
 10  company_rating      5000 non-null   float64
 11  date_posted         5000 non-null   str
 12  company_id          5000 non-null   str
 13  location_id         5000 non-null   str
dtypes: float64(2), int64(2), str(10)
memory usage: 547.0 KB

In [61]:
Company_table.to_sql(
    name="company_table",
    con=engine,
    if_exists="append",
    index=False
)

Location_table.to_sql(
    name="location_table",
    con=engine,
    if_exists="append",
    index=False
)

Fact_table.to_sql(
    name="fact_table",
    con=engine,
    if_exists="append",
    index=False
)

print("Data loaded successfully!")

Data loaded successfully!

In [62]:
with engine.connect() as conn:

    print(conn.execute(text("SELECT COUNT(*) FROM Company_table")).scalar())
    print(conn.execute(text("SELECT COUNT(*) FROM Location_table")).scalar())
    print(conn.execute(text("SELECT COUNT(*) FROM Fact_table")).scalar())

714
17
5000